import { Contract } from "@/domain/types/Contract";

export const mockContracts: Contract[] = [
  {
    id: "1",
    contractNumber: "IT-2023-0001",
    title: "Website Development Services",
    description: "Development of a new corporate website with content management system",
    vendor: "TechSolutions Inc.",
    amount: 45000,
    startDate: "2023-06-01",
    endDate: "2023-12-31",
    status: "ExecutedActive",
    type: "services",
    department: "Information Technology",
    accountingCodes: "IT-DEV-2023",
    vendorEmail: "contact@techsolutions.com",
    vendorPhone: "555-123-4567",
    vendorAddress: "123 Tech Lane, San Francisco, CA 94107",
    signatoryName: "Jane Smith",
    signatoryEmail: "jane.smith@techsolutions.com",
    attachments: [],
    comments: [],
    creatorId: "user-1",
    creatorEmail: "admin@example.com",
    createdAt: "2023-05-15T10:30:00Z"
  },
  {
    id: "2",
    contractNumber: "HR-2023-0002",
    title: "Employee Training Program",
    description: "Comprehensive training program for new hires and existing staff",
    vendor: "Learning Partners LLC",
    amount: 28500,
    startDate: "2023-07-15",
    endDate: "2024-01-15",
    status: "ExecutedActive",
    type: "services",
    department: "Human Resources",
    accountingCodes: "HR-TRN-2023",
    vendorEmail: "info@learningpartners.com",
    vendorPhone: "555-987-6543",
    vendorAddress: "456 Education Ave, Boston, MA 02108",
    signatoryName: "Robert Johnson",
    signatoryEmail: "robert@learningpartners.com",
    attachments: [],
    comments: [],
    creatorId: "user-2",
    creatorEmail: "hr@example.com",
    createdAt: "2023-06-20T14:45:00Z"
  },
  {
    id: "3",
    contractNumber: "MKT-2023-0003",
    title: "Digital Marketing Campaign",
    description: "Q3 digital marketing campaign across social media platforms",
    vendor: "MediaMax Marketing",
    amount: 35000,
    startDate: "2023-07-01",
    endDate: "2023-09-30",
    status: "Review",
    type: "services",
    department: "Marketing",
    accountingCodes: "MKT-DIG-2023",
    vendorEmail: "campaigns@mediamax.com",
    vendorPhone: "555-789-0123",
    vendorAddress: "789 Media Blvd, New York, NY 10001",
    signatoryName: "Sarah Williams",
    signatoryEmail: "sarah@mediamax.com",
    attachments: [],
    comments: [],
    creatorId: "user-3",
    creatorEmail: "marketing@example.com",
    createdAt: "2023-06-15T09:15:00Z"
  }
]; 