project_id = "bobzoageocfbstkxmrmx"
[functions.clerk-webhooks]
enabled = true
verify_jwt = true
import_map = "./functions/clerk-webhooks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clerk-webhooks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clerk-webhooks/*.html" ]

[functions.clerk-sync]
enabled = true
verify_jwt = true
import_map = "./functions/clerk-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clerk-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clerk-sync/*.html" ]
