// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bobzoageocfbstkxmrmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvYnpvYWdlb2NmYnN0a3htcm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTI1NDQsImV4cCI6MjA1NTg2ODU0NH0.Qn28eAfAM3UrQw7sGskpVAo_SPLk8QQD74qby_5psyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);